GET http://localhost:8000/diniy
###
GET http://localhost:8000/users/1

###
POST http://localhost:8000/users
Content-Type: application/json
{
    "nama":"Gabriel Arta Pratama Sidauruk",
    "email":"gpratama796@gmail.com",
    "gender":"Laki-laki",
    "kec1" : 11,
    "kec2" : 11,
    "kec3" : 11,
    "kec4" : 11,
    "kec5" : 11,
    "kec6" : 11,
    "kec7" : 11,
    "kec8" : 11,
    "kec9" : 11


}